import { FileItem } from "./types";

export const mockFiles: FileItem[] = [
  {
    id: "folder1",
    name: "آزمایشات خون",
    type: "folder",
    size: "",
    uploadDate: "1403/08/15",
    category: "lab-result",
    isFolder: true,
  },
  {
    id: "1",
    name: "گزارش آزمایش خون کامل.pdf",
    type: "application/pdf",
    size: "2.4 MB",
    uploadDate: "1403/08/15",
    category: "lab-result",
    parentId: "folder1",
    analysis: {
      id: "analysis1",
      fileName: "گزارش آزمایش خون کامل.pdf",
      summary:
        "نتایج آزمایش خون نشان‌دهنده سطح طبیعی اکثر پارامترها است. قند خون و کلسترول در محدوده مطلوب قرار دارند.",
      keyFindings: [
        "قند خون: 95 mg/dL (طبیعی)",
        "کلسترول کل: 180 mg/dL (مطلوب)",
        "هموگلوبین: 13.5 g/dL (طبیعی)",
        "پلاکت: 250,000 (طبیعی)",
      ],
      questions: [
        "آیا نیاز به تکرار این آزمایش دارم؟",
        "چه رژیم غذایی برای حفظ این وضعیت مناسب است؟",
        "کدام ویتامین‌ها را باید مصرف کنم؟",
      ],
      analysisDate: "1403/08/15",
      status: "completed",
    },
  },
  {
    id: "2",
    name: "آزمایش ادرار.pdf",
    type: "application/pdf",
    size: "1.2 MB",
    uploadDate: "1403/08/14",
    category: "lab-result",
    parentId: "folder1",
  },
  {
    id: "folder2",
    name: "تصاویر رادیولوژی",
    type: "folder",
    size: "",
    uploadDate: "1403/08/14",
    category: "xray",
    isFolder: true,
  },
  {
    id: "3",
    name: "عکس رادیولوژی قفسه سینه.jpg",
    type: "image/jpeg",
    size: "1.8 MB",
    uploadDate: "1403/08/14",
    category: "xray",
    parentId: "folder2",
  },
  {
    id: "4",
    name: "سی‌تی اسکن مغز.dcm",
    type: "application/dicom",
    size: "25.6 MB",
    uploadDate: "1403/08/13",
    category: "xray",
    parentId: "folder2",
  },

  {
    id: "folder4",
    name: "تصاویر NIfTI",
    type: "folder",
    size: "",
    uploadDate: "1403/08/16",
    category: "nifti",
    isFolder: true,
  },
  {
    id: "nifti1",
    name: "000007_03_01.nii.gz",
    type: "application/nifti",
    size: "12.8 MB",
    uploadDate: "1403/08/16",
    category: "nifti",
    parentId: "folder4",
    metadata: {
      dimensions: [512, 512, 30],
      pixelSpacing: [0.5, 0.5, 5.0],
      orientation: "Axial",
      dataType: "float32",
      slices: 30,
      acquisitionDate: "1403/08/15",
      patientInfo: {
        age: "45",
        sex: "مرد",
        studyDescription: "MRI مغز با کنتراست",
      },
    },
    analysis: {
      id: "analysis_nifti1",
      fileName: "000007_03_01.nii.gz",
      summary:
        "تصاویر MRI مغز نشان‌دهنده ساختار طبیعی بافت مغزی است. هیچ ضایعه یا ناهنجاری قابل توجهی مشاهده نمی‌شود.",
      keyFindings: [
        "بافت مغزی طبیعی",
        "عدم وجود تومور یا ضایعه",
        "سیستم بطنی طبیعی",
        "عروق مغزی سالم",
      ],
      questions: [
        "آیا نیاز به تکرار MRI دارم؟",
        "چه اقداماتی برای حفظ سلامت مغز لازم است؟",
        "کدام علائم نگران‌کننده هستند؟",
      ],
      analysisDate: "1403/08/16",
      status: "completed",
    },
  },
  {
    id: "nifti2",
    name: "000016_01_01.nii.gz",
    type: "application/nifti",
    size: "15.2 MB",
    uploadDate: "1403/08/16",
    category: "nifti",
    parentId: "folder4",
    metadata: {
      dimensions: [256, 256, 50],
      pixelSpacing: [0.7, 0.7, 3.0],
      orientation: "Sagittal",
      dataType: "int16",
      slices: 50,
      acquisitionDate: "1403/08/15",
      patientInfo: {
        age: "32",
        sex: "زن",
        studyDescription: "fMRI مطالعه فعالیت مغزی",
      },
    },
  },
  {
    id: "folder3",
    name: "گزارش‌های پزشکی",
    type: "folder",
    size: "",
    uploadDate: "1403/08/13",
    category: "medical-report",
    isFolder: true,
  },
  {
    id: "5",
    name: "نسخه پزشک.pdf",
    type: "application/pdf",
    size: "0.9 MB",
    uploadDate: "1403/08/13",
    category: "medical-report",
    parentId: "folder3",
  },
];
